/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldRouteImport } from './routes/yield'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PerpsRouteImport } from './routes/perps'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenMintRouteImport } from './routes/token.$mint'

const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerpsRoute = PerpsRouteImport.update({
  id: '/perps',
  path: '/perps',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenMintRoute = TokenMintRouteImport.update({
  id: '/token/$mint',
  path: '/token/$mint',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/pulse': typeof PulseRoute
  '/yield': typeof YieldRoute
  '/token/$mint': typeof TokenMintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/pulse': typeof PulseRoute
  '/yield': typeof YieldRoute
  '/token/$mint': typeof TokenMintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/pulse': typeof PulseRoute
  '/yield': typeof YieldRoute
  '/token/$mint': typeof TokenMintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/perps'
    | '/portfolio'
    | '/pulse'
    | '/yield'
    | '/token/$mint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/perps'
    | '/portfolio'
    | '/pulse'
    | '/yield'
    | '/token/$mint'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/perps'
    | '/portfolio'
    | '/pulse'
    | '/yield'
    | '/token/$mint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  PerpsRoute: typeof PerpsRoute
  PortfolioRoute: typeof PortfolioRoute
  PulseRoute: typeof PulseRoute
  YieldRoute: typeof YieldRoute
  TokenMintRoute: typeof TokenMintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perps': {
      id: '/perps'
      path: '/perps'
      fullPath: '/perps'
      preLoaderRoute: typeof PerpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$mint': {
      id: '/token/$mint'
      path: '/token/$mint'
      fullPath: '/token/$mint'
      preLoaderRoute: typeof TokenMintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  PerpsRoute: PerpsRoute,
  PortfolioRoute: PortfolioRoute,
  PulseRoute: PulseRoute,
  YieldRoute: YieldRoute,
  TokenMintRoute: TokenMintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
